// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3LjVt6_QVgVg7HqDI8soRIZo2MJpmwoM',
    appId: '1:85920320638:android:071b4c076b716105d2dc2f',
    messagingSenderId: '85920320638',
    projectId: 'muslimlife-372e2',
    storageBucket: 'muslimlife-372e2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7owFfpoeytS4CLlo6__8kiMNftpqLI40',
    appId: '1:85920320638:ios:df62066706ff6c18d2dc2f',
    messagingSenderId: '85920320638',
    projectId: 'muslimlife-372e2',
    storageBucket: 'muslimlife-372e2.firebasestorage.app',
    iosBundleId: 'com.muslimlife.muslimlife',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuhVKvAZpAmawUYRYEO-nuidhrre4T6fY',
    appId: '1:85920320638:web:0f0de6bf0d6c47cbd2dc2f',
    messagingSenderId: '85920320638',
    projectId: 'muslimlife-372e2',
    authDomain: 'muslimlife-372e2.firebaseapp.com',
    storageBucket: 'muslimlife-372e2.firebasestorage.app',
    measurementId: 'G-6C2R0X4870',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7owFfpoeytS4CLlo6__8kiMNftpqLI40',
    appId: '1:85920320638:ios:3699ff03c5d34233d2dc2f',
    messagingSenderId: '85920320638',
    projectId: 'muslimlife-372e2',
    storageBucket: 'muslimlife-372e2.firebasestorage.app',
    iosBundleId: 'com.netrosystems.muslimlife',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuhVKvAZpAmawUYRYEO-nuidhrre4T6fY',
    appId: '1:85920320638:web:e2f1aa2fbad393a5d2dc2f',
    messagingSenderId: '85920320638',
    projectId: 'muslimlife-372e2',
    authDomain: 'muslimlife-372e2.firebaseapp.com',
    storageBucket: 'muslimlife-372e2.firebasestorage.app',
    measurementId: 'G-B2XPCY5E38',
  );

}